name: 'API specification retriever'
description: 'Fetch API specifications from GitHub'
inputs:
  source-api-key:
    description: 'GitHub API key for source repository'
    required: true
  source-owner:
    description: 'Source repository owner (e.g. org)'
    required: true
  source-repo:
    description: 'Source repository name'
    required: true
  dest-api-key:
    description: 'GitHub API key for destination repository'
    required: true
  dest-owner:
    description: 'Destination repository owner (e.g. org)'
    required: true
  dest-repo:
    description: 'Destination repository name'
    required: true
  temp-dir:
    description: 'Temporary directory to store release asset files'
    required: true
    default: './files'
  body-replace-regex:
    description: 'Regular expression to replace in release body'
    required: false
  body-replace-with:
    description: 'Replacement string for regular expression'
    required: false
  release-name:
    description: 'Name of the release to copy'
    required: true
    default: ''
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SOURCE_API_KEY: "${{ inputs.source-api-key }}"
    SOURCE_OWNER: "${{ inputs.source-owner }}"
    SOURCE_REPO: "${{ inputs.source-repo }}"
    DEST_API_KEY: "${{ inputs.dest-api-key }}"
    DEST_OWNER: "${{ inputs.dest-owner }}"
    DEST_REPO: "${{ inputs.dest-repo }}"
    TEMP_DIR: "${{ inputs.temp-dir }}"
    BODY_REPLACE_REGEX: "${{ inputs.body-replace-regex }}"
    BODY_REPLACE_WITH: "${{ inputs.body-replace-with }}"
  args: [ "${{ inputs.release-name }}" ]
